### ISSUE TITLE
Can i use the Qualcomm Atheros QCA9565 kext for qualcm qca9377 wireless adapter 

### ISSUE THREAD

**Issue by KavyanshJain** [asepms92/Hackintosh-ASUS-A455LF-Notebook#10]
I want to install hackintosh big sur on my pc (Dell Vostro 3581) but i search everywhere there is no kext for my wireless adapter my adapter is 2 in 1 it have buletooth connectivity also can this kext work for it also or if you some other solution so plz provide me 

Thanks to hear my problem

**Comment by SpaceFlight21** [comment]
You will just have to try it out. (You can try it out on virtual machine)
