### ISSUE TITLE
Pertanyaan Simple Bro

### ISSUE THREAD

**Issue by muhrizkiakbar** [asepms92/Hackintosh-ASUS-A455LF-Notebook#11]
Bro, gw udh sukses install catalina, tapi ada yg masih error, cara fix nya gimana yaa? Apa make kext dari mas bro?

**Comment by asepms92** [comment]
> Bro, gw udh sukses install catalina, tapi ada yg masih error, cara fix nya gimana yaa? Apa make kext dari mas bro?

Dah tak update..
