### ISSUE TITLE
Stuck at Apple Logo

### ISSUE THREAD

**Issue by anjarhariadi** [asepms92/Hackintosh-ASUS-A455LF-Notebook#12]
Bro, i was tried this OC configuration to install Hackintosh Mojave in my ASUS A455LF with Intel Core I3-5005U (Broadwell).
For the first time boot for installing in Harddisk, everything is working really fine,
But at the second boot after installing process was done, i get stuck at Apple logo.
Can you explain to me whats wrong possibility and how can i fix this? Thanks

**Comment by asepms92** [comment]
Try to disable CSM on BIOS, can you post the screenshot?
