### ISSUE TITLE
Tentang BIOS

### ISSUE THREAD

**Issue by likin1234** [asepms92/Hackintosh-ASUS-A455LF-Notebook#13]
Bro, sebelumnya terimakasih banyak karena apa yg bro buat ini sangat membantu saya yg punya laptop sama persis, cuman beda di versi bios.
Nah...saya sudah coba untuk update bios tapi kok tidak ada respon ya bro....
- apakah saya salah donlod file bios-nya?
- sudah saya coba bios simpan di HDD windows - gagal tidak ada respon
- sudah saya coba bios simpan di FDD (fornat ntfs-fat32) - gagal tidak ada respon
- mau coba browsing lagi ke web asus - sedang maintenance
 We'll be back.
Hi, our website is temporarily closed for service enhancements.
We'll be back shortly.Thank you for your patience!
- ini nama file bios yg sy donlod : X455LFAS302
- saya dual boot beda HDD : macos SSD, windows10 HDD

keterangan : 'gagal tidak ada respon' = file bios sudah dikenali - klik update - pas sudah msuk ke laman tersebut, tapi tidak muncul progress yang ada garis hijau itu.

![update-asus-bios](https://user-images.githubusercontent.com/96687221/147408699-708f7c04-3c24-44a0-a14d-2d82aa510fb7.jpg)

mohon dibantu sekiranya ada petunjuk tertentu utk update bios.
Sekali lagi terimakasih

**Comment by asepms92** [comment]
> Bro, sebelumnya terimakasih banyak karena apa yg bro buat ini sangat membantu saya yg punya laptop sama persis, cuman beda di versi bios. Nah...saya sudah coba untuk update bios tapi kok tidak ada respon ya bro....
> 
> * apakah saya salah donlod file bios-nya?
> * sudah saya coba bios simpan di HDD windows - gagal tidak ada respon
> * sudah saya coba bios simpan di FDD (fornat ntfs-fat32) - gagal tidak ada respon
> * mau coba browsing lagi ke web asus - sedang maintenance
>   We'll be back.
>   Hi, our website is temporarily closed for service enhancements.
>   We'll be back shortly.Thank you for your patience!
> * ini nama file bios yg sy donlod : X455LFAS302
> * saya dual boot beda HDD : macos SSD, windows10 HDD
> 
> keterangan : 'gagal tidak ada respon' = file bios sudah dikenali - klik update - pas sudah msuk ke laman tersebut, tapi tidak muncul progress yang ada garis hijau itu.
> 
> ![update-asus-bios](https://user-images.githubusercontent.com/96687221/147408699-708f7c04-3c24-44a0-a14d-2d82aa510fb7.jpg)
> 
> mohon dibantu sekiranya ada petunjuk tertentu utk update bios. Sekali lagi terimakasih

Coba CFG-lock disable dulu, saya dulu juga gitu pas habis ganti baterai, pake metode [ini](https://akhmad.id/blog/disable-cfg-lock-pada-acer-e5-476g/)

Bongkar file BIOSnya pake tools di link atas, nanti ketemu di bagian setup yang berhubungan dengan CPU
![162410845_4553382914688203_1470229088778654995_n](https://user-images.githubusercontent.com/43111808/147416502-63ff229b-9d60-4d05-8697-0757536df31c.jpg)

Nanti di bagian Values 0088 biasanya ada value 01, ganti ke 00, lalu save update BIOSnya.. nanti jangan di Restore defaults lagi di BIOS bakal balik lagi ke semula
![162435759_4553392844687210_5759240262756318416_n](https://user-images.githubusercontent.com/43111808/147416547-1f327cbb-31e6-49a6-8f2a-adc9ee2dfdae.jpg)

**Comment by likin1234** [comment]
Terimakasih banyak bro atas atensi-nya....
Sudah bisa bro...iseng sy coba reset nvram - masuk bios - update 'start easy flash' - done.
.
.
Trims ya bro...salam.
happy early new year 2022.
