### ISSUE TITLE
Ijin bertanya mengenai USB

### ISSUE THREAD

**Issue by likin1234** [asepms92/Hackintosh-ASUS-A455LF-Notebook#14]
Bro, ijin bertanya mengenai USB ports/mapping/dlsb...
Sebelum ke MacOS Big Sur, saya pernah/lama dengan MacOs Mojave-Clover.
Nah ketika bikin Hackintosh Mojave, saya pernah mapping USB ports-nya (metode Rehabman di tonymacx86), dan berhasil.
Sekarang ini di Big Sur-Open Core, saya full memakai OC yang bro bikin (terimakasih banyak), kemudian bermaksud mau pakai mapping USB ports yg saya bikin di mojave tapi bingung mau kombinasikan/menggantikan dengan usb mapped-OC yg bro bikin.
Mohon petunjuknya seandainya bisa merge / mungkin edit dgn usb mapped-OC yang bro bikin......
*salah satu tujuannya adalah utk mengaktifkan Card Reader-nya.

Berikut hasil mapping usb ports saya di MacOS Mojave dgn Clover :
[USB.pdf](https://github.com/asepms92/Hackintosh-ASUS-A455LF-Notebook/files/7881440/USB.pdf)
[usbssdt+kext.zip](https://github.com/asepms92/Hackintosh-ASUS-A455LF-Notebook/files/7881429/usbssdt%2Bkext.zip)

USB mapped : 
![USB mapped](https://user-images.githubusercontent.com/96687221/149760125-05b40835-cc71-4170-8566-a6991a269248.jpg)

HS01 USB2 device on USB3 ports : 
![HS01 USB2 device on USB3 ports](https://user-images.githubusercontent.com/96687221/149760308-e670f90d-8c52-4a85-84c2-339cd145c332.png)

HS05 webcam : 
![HS05 webcam](https://user-images.githubusercontent.com/96687221/149760326-d405986c-3228-4dae-bbf1-10df2dc66a5d.png)

HS06 Bluetooth : 
![HS06 Bluetooth](https://user-images.githubusercontent.com/96687221/149760343-bad18656-1ed3-45b9-9ad1-2fdb2e674d5f.png)

HS08 Card Reader : 
![HS08 Card Reader](https://user-images.githubusercontent.com/96687221/149760355-8213433c-378f-4e48-9de1-2983a4de0922.png)

SS01 USB3 device on USB3 ports : 
![SS01 USB3 device on USB3 ports](https://user-images.githubusercontent.com/96687221/149760370-3cfc805e-5ab4-41a3-817c-c828feeb0252.png)

Terimakasih banyak sebelumnya....

**Comment by asepms92** [comment]
Patokannya kembali ke device masing2, soalnya beda port beda lagi konfigurasinya.. Test di windows plug & unplug port apa aja yang aktif bisa pake [tool ini](https://github.com/USBToolBox/tool) atau di macOS bisa pake [ini ](https://github.com/corpnewt/USBMap.git).. Kalo sebelumnya dah pernah mapping di Mojave, ya tinggal pake aja configurasi mappingnya, yang penting semua ports dah bener.. testing sleep/wake laptopnya atau restart masalah bisa jadi karena salah mapping USB..

**Comment by asepms92** [comment]
Kalo sebelumnya mapping USBnya via kext tinggal edit info.plist di bagian CFBundleIdentifier = com.apple.driver.AppleUSBMergeNub (Untuk Catalina ke bawah) -> com.apple.driver.AppleUSBHostMergeProperties (Untuk Big Sur ke atas), bisa lihat contohnya di repo [ini](https://github.com/asepms92/Hackintosh-ASUS-A455LF-Notebook/blob/master/CLOVER/EFI/CLOVER/kexts/Other/USBMap.kext/Contents/Info.plist#L229)

**Comment by likin1234** [comment]
> Kalo sebelumnya mapping USBnya via kext tinggal edit info.plist di bagian CFBundleIdentifier = com.apple.driver.AppleUSBMergeNub (Untuk Catalina ke bawah) -> com.apple.driver.AppleUSBHostMergeProperties (Untuk Big Sur ke atas), bisa lihat contohnya di repo [ini](https://github.com/asepms92/Hackintosh-ASUS-A455LF-Notebook/blob/master/CLOVER/EFI/CLOVER/kexts/Other/USBMap.kext/Contents/Info.plist#L229)

hmmm...sekilas kalau lihat petunjuk bro diatas dan membandingkan dengan mapping usb saya waktu di mojave, perbedaannya ada di port HS08 yg menurut saya berkorelasi dengan Card Reader.

USBMap.kext/Contents/Info.plist
![Capture](https://user-images.githubusercontent.com/96687221/149856559-50a6e273-bffb-4b56-ba8d-eb2178388b70.PNG)

port HS08 yg menurut saya berkorelasi dengan Card Reader
![CardReader](https://user-images.githubusercontent.com/96687221/149856596-760f21c3-068f-4a2b-a71d-898f7cc001b7.jpg)

Pertanyaannya, apakah karena ada 1 dan lain hal, Card Reader memang tidak bisa diaktifkan?

**Comment by asepms92** [comment]
Di mojave work-kah Card readernya? coba metode lama yg [ini](https://www.tonymacx86.com/threads/how-to-make-a-generic-driver-for-any-card-reader.74471/) copy kextnya, inject di bootloader, atau coba yang [ini](https://github.com/0xFireWolf/GenericCardReaderFriend), edit Info.plistnya.. idProduct (0x6366 = 25446), idVendor (0x058f = 1423)
