### ISSUE TITLE
Layar blank setelah boot apple

### ISSUE THREAD

**Issue by Irfan234-afif** [asepms92/Hackintosh-ASUS-A455LF-Notebook#15]
saya telah melakukan berbagai cara untuk itu, hanya ingin sekedar tahu, kenapa kok nggak bisa di laptop saya, ASUS A455LJ Intel Core I3-5010U

Kemarin saya mencoba mengcopy satu persatu struktur EFI mas asep ke EFI saya sendiri yang work, dari awal nya SSDT dan itu work semua, kext work, lalu saya melakukan copy config.plist per-children, dan  awalnya bisa sampai waktu saya copy DevicesProperties, bug itu terjadi lagi, layar blank setelah boot APPLE

**Comment by asepms92** [comment]
> saya telah melakukan berbagai cara untuk itu, hanya ingin sekedar tahu, kenapa kok nggak bisa di laptop saya, ASUS A455LJ Intel Core I3-5010U
> 
> Kemarin saya mencoba mengcopy satu persatu struktur EFI mas asep ke EFI saya sendiri yang work, dari awal nya SSDT dan itu work semua, kext work, lalu saya melakukan copy config.plist per-children, dan awalnya bisa sampai waktu saya copy DevicesProperties, bug itu terjadi lagi, layar blank setelah boot APPLE

Blank setelah nambah PCI Device di DeviceProperties-kah? kalo iya undo/hapus lagi kecuali untuk IGPU, bisa cek di Hackintool, soalnya beda2 IOName/AAPL,slot-name, vendor-id/subsystem-vendor-id, dll..

**Comment by Irfan234-afif** [comment]
ngga ada tambah apa apa mas langsung pakai

**Comment by Irfan234-afif** [comment]
okei saya coba mas
