### ISSUE TITLE
[Ask] Laptop nya sama

### ISSUE THREAD

**Issue by muhrizkiakbar** [asepms92/Hackintosh-ASUS-A455LF-Notebook#2]
Versio bios nya brp ?
langkah install nya ada? setting bios dan lain2 ?

**Comment by faza76** [comment]
sir are you know how to disable the nvidia 930m ? we have same bios version but i can't find option to disable my nvidia card, can you share your method please ?

**Comment by muhrizkiakbar** [comment]
> sir are you know how to disable the nvidia 930m ? we have same bios version but i can't find option to disable my nvidia card, can you share your method please ?

up up

**Comment by asepms92** [comment]
> > sir are you know how to disable the nvidia 930m ? we have same bios version but i can't find option to disable my nvidia card, can you share your method please ?
> 
> up up

Done..
