### ISSUE TITLE
How to disable nvidia in bios

### ISSUE THREAD

**Issue by faza76** [asepms92/Hackintosh-ASUS-A455LF-Notebook#3]
sir are you know how to disable the nvidia 930m ? we have same bios version but i can't find option to disable my nvidia card, can you share your method please ?

**Comment by asepms92** [comment]
> sir are you know how to disable the nvidia 930m ? we have same bios version but i can't find option to disable my nvidia card, can you share your method please ?

Done, Updated & rework to latest version
