### ISSUE TITLE
how to use CustomPeripheral.kext

### ISSUE THREAD

**Issue by wklxd** [asepms92/Hackintosh-ASUS-A455LF-Notebook#5]
hello, I have a matebook 13 2019 laptop, my camera is 13D3:56C6，and the camera can found by macOS，but can not  use（black screen in photo booth)

can I use CustomPeripheral.kext to do something, to make camera work?

**Comment by asepms92** [comment]
Load from VMWare or from iCloud for change your picture.. then load again to photo booth..

yes you can use CustomPeripheral.kext, just edit info.plist.. my camera 1266 (0x04F2) : 46211 (0xB483) and merge to id Product & id Vendor Apple like native built-in 1452 (0x05AC) : 34057 (0x8509)
![Screen Shot 2020-06-21 at 00 54 51](https://user-images.githubusercontent.com/43111808/85208402-66b83c00-b35a-11ea-9884-8d31b77972aa.png)

**Comment by wklxd** [comment]
yeah， many thanks，I will try
