### ISSUE TITLE
I have no idea how to install Hackintosh

### ISSUE THREAD

**Issue by doghuang** [asepms92/Hackintosh-ASUS-A455LF-Notebook#6]
My computer model is asus A555LF.We have same BIOS model(version 601),same processors(i5-5200u),same graphics(Intel HD 5500,nvidia 930m).But I have a black screen during installation.
Sorry to interrupt…

**Comment by asepms92** [comment]
Make your own USB installer, download .dmg from App Store, create your config and set EFI for your device, i'm using config from RehabMan and some modifications for USB installer..

boot-args with verbose (-v) and send your log or Screenshot if you have problems or stuck on black screen..

**Comment by doghuang** [comment]
Thank you.But I can't configure the EFI file.Can I just use yours?

**Comment by asepms92** [comment]
I'm not sure My EFI for USB installer, just only for succesful installation to HDD/SSD..
