### ISSUE TITLE
Big Sur Beta

### ISSUE THREAD

**Issue by dheiro** [asepms92/Hackintosh-ASUS-A455LF-Notebook#9]
are you try this laptop for Big Sur Beta? 
please share your experience if done

i use this for Asus A455LB, all working/not working listed in description is valid

HDMI tested running well on LG 34WN80C-B 34 Inch 21:9 UltraWide™ WQHD IPS HDR10

**Comment by RidhaAF** [comment]
> are you try this laptop for Big Sur Beta?
> please share your experience if done
> 
> i use this for Asus A455LB, all working/not working listed in description is valid
> 
> HDMI tested running well on LG 34WN80C-B 34 Inch 21:9 UltraWide™ WQHD IPS HDR10

bisa boot dual screen pake HDMI ga bro? saya kalo boot langsung colok HDMI, layar laptop mati, monitor nyala.
tapi kalo boot tanpa HDMI, terus pas udah masuk desktop baru colok HDMI aman jadi dual screen

**Comment by dheiro** [comment]
> > are you try this laptop for Big Sur Beta?
> > please share your experience if done
> > i use this for Asus A455LB, all working/not working listed in description is valid
> > HDMI tested running well on LG 34WN80C-B 34 Inch 21:9 UltraWide™ WQHD IPS HDR10
> 
> bisa boot dual screen pake HDMI ga bro? saya kalo boot langsung colok HDMI, layar laptop mati, monitor nyala.
> tapi kalo boot tanpa HDMI, terus pas udah masuk desktop baru colok HDMI aman jadi dual screen

bisa, tapi sepertinya beda monitor beda atau entah lah, soalnnya di monitor satunya LG 4K 27 inch normal aja tapi pas di colok monitor 34 inch WQHD logo asusnya ikut masuk monitor pas baru nyala
